## cartridge.properties for cartridge app_custom_amplience
demandware.cartridges.app_custom_amplience.id=app_custom_amplience
demandware.cartridges.app_custom_amplience.multipleLanguageStorefront=true
