## cartridge.properties for cartridge app_custom_royalcyber
demandware.cartridges.app_custom_royalcyber.id=app_custom_royalcyber
demandware.cartridges.app_custom_royalcyber.multipleLanguageStorefront=true
